# Generated by Django 3.1.4 on 2020-12-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201225_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appeal_points',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='アピールポイント'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name_furigana',
            field=models.CharField(default='aa', max_length=255, verbose_name='会社名フリガナ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='established_at',
            field=models.DateField(default='2020-12-2', verbose_name='創業'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='major_clients',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='主な取引先'),
        ),
        migrations.AddField(
            model_name='user',
            name='major_facilities',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='主な施設'),
        ),
        migrations.AddField(
            model_name='user',
            name='major_products',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='主な製品'),
        ),
        migrations.AddField(
            model_name='user',
            name='major_technologies',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='主な技術'),
        ),
        migrations.AddField(
            model_name='user',
            name='poc_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='user',
            name='representative_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(default='', max_length=255, verbose_name='会社概要'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='website'),
        ),
    ]
