# Generated by Django 3.1.4 on 2020-12-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201225_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='established_at',
            field=models.IntegerField(verbose_name='創業'),
        ),
    ]
