# Generated by Django 3.1.4 on 2020-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201225_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='established_at',
            field=models.CharField(choices=[('1900', '1900')], max_length=100, verbose_name='創業'),
        ),
    ]
