# Generated by Django 3.1.4 on 2020-12-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201225_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appeal_points',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='アピールポイント'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_clients',
            field=models.TextField(blank=True, default='', verbose_name='主な取引先'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_facilities',
            field=models.TextField(blank=True, default='', verbose_name='主な施設'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_products',
            field=models.TextField(blank=True, default='', verbose_name='主な製品'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_technologies',
            field=models.TextField(blank=True, default='', verbose_name='主な技術'),
        ),
        migrations.AlterField(
            model_name='user',
            name='poc_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='website'),
        ),
    ]
