# Generated by Django 3.1.4 on 2020-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201226_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='', verbose_name='サムネイル'),
        ),
    ]
